try {
const myFunc = {};
myFunc();
} catch(err) {
  console.log("oops something went wrong!")
}
console.log("Im here!!");